# containers
sudo: false

language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-111
    - python: 3.4
      env: TOXENV=py34-111
    - python: 3.4
      env: TOXENV=py34-20
    - python: 3.5
      env: TOXENV=py35-111
    - python: 3.5
      env: TOXENV=py35-20
    - python: 3.5
      env: TOXENV=py35-21
    - python: 3.6
      env: TOXENV=py36-111
    - python: 3.6
      env: TOXENV=py36-20
    - python: 3.6
      env: TOXENV=py36-21
    - python: 3.7-dev
      env: TOXENV=py37-20
    - python: 3.7-dev
      env: TOXENV=py37-21

# command to install dependencies
install:
  - pip install tox

# command to run tests
script:
  - tox -e $TOXENV
