language: python
python: 3.5
env:
  - TOX_ENV=py27-17
  - TOX_ENV=py27-18
  - TOX_ENV=py27-19
  - TOX_ENV=py33-17
  - TOX_ENV=py33-18
  - TOX_ENV=py34-17
  - TOX_ENV=py34-18
  - TOX_ENV=py34-19
  - TOX_ENV=py35-18
  - TOX_ENV=py35-19
# command to install dependencies
install:
  - pip install tox
# command to run tests
script:
  - tox -e $TOX_ENV
# containers
sudo: false
